spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/devarchive?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true # data.sql을 위한 필수 설정
    hibernate:
      ddl-auto: create-drop # 테이블 자동 생성 (개발 단계)
    show-sql: true     # 실행되는 SQL문 콘솔 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # 이 부분은 건드리지 마세요!
        
server:
  error:
    whitelabel:
      enabled: true